### ISSUE TITLE
Back button not working correctly on Firefox 40.0.3, Windows 8.1

### ISSUE THREAD

**Issue by niksilver** [guardian/frontend#10331]
Bug occurs on Firefox 40.0.3 (and some previous versions from memory). Does not occur on IE11. Both tested on Windows 8.1.

Steps to reproduce:

1. Open a new browser tab. (This seems to be an important step.)
1. Go to http://theguardian.com by typing it directly into the location box.
1. Click on a link on the home page. Today I chose http://www.theguardian.com/commentisfree/2015/aug/31/serena-williams-best-because-brains-not-body
1. Notice the browser's Back/Forward buttons are displaying correctly: Only Back is active; there is no Forward button.
1. Click the browser's Back button.
1. Then...
  * What actually happens: The page doesn't change at all. But the browser's Forward button becomes active.
  * What should happen: The page should go back to the home page.

Once we've got to that point we can then continue to find more weirdness:
1. Click on another link. I chose http://www.theguardian.com/sport/serena-williams
1. Click the Back button again.
1. Then...
  * What actually happens: The page goes back to the original article (good!) but the now the browser's Forward button is not active.
  * What should have happened: The page should indeed have gone back to the original article, but the browser's Forward button should be active.

**Comment by paperboyo** [comment]
Thanks for filing! I can't reproduce it in FF 40.0.3 on 10.9.5, but I have definitely experienced it in the past. Will try to reproduce on Windows.

Very slightly related to: https://github.com/guardian/frontend/issues/6144

**Comment by paperboyo** [comment]
Can’t reproduce in FF 41.0ß5 and 43.0α1 on Win 10. Ideally, we would need a 100% reproducible procedure...

**Comment by niksilver** [comment]
@paperboyo I couldn't reproduce it just now on Windows 7. But I've experienced it today on Windows 8.1. Appreciate you need a 100% reproducible procedure, so try Windows 8.1.

**Comment by niksilver** [comment]
@paperboyo Apologies for almost-immediate follow-up, and this comment is not hugely helpful, but...

I'm using the site again on Windows 7 Firefox 40.0.3. And although I couldn't reproduce the bug on that setup last night (see my last comment), I can now. However I cannot reproduce it 100%. The steps above to reproduce are the same, but it just doesn't happen 100% of the time. It is inconsistent even on the same article.

Do with this information what you will...

**Comment by mattandrews** [comment]
Opening the site in a new tab in Firefox cause a JS error which prevents comments/images from loading. Some details here: https://github.com/guardian/frontend/issues/8338

**Comment by paperboyo** [comment]
Reproduced on FF on Win 8.1 (testing machine).

**Comment by desbo** [comment]
I've reproduced this on OSX FF v40.0.3. Something's causing a duplicate entry to be added to the history, so hitting back sends you to the same page. Here's my history after reproducing the bug:

![screen shot 2015-09-08 at 11 55 28](https://cloud.githubusercontent.com/assets/1064734/9733114/b388c0c8-5620-11e5-9e2d-0290512ba9a1.png)

A bit of digging suggests this can happen when you change the `src` of an iframe, which sounds like something ads might do. No fix yet, but I'll keep looking.

**Comment by paperboyo** [comment]
re:https://github.com/guardian/frontend/issues/10331#issuecomment-137420712 reproduced on 41.0b8 on Win 10:

![new-tab_1](https://cloud.githubusercontent.com/assets/6032869/9786637/89cf23a0-57b3-11e5-90cc-3fb7ee68e69b.gif)

**Comment by paperboyo** [comment]
Hi, @niksilver. This looks like it’s fixed now (by https://github.com/guardian/frontend/pull/10829). Could you confirm, please?

**Comment by niksilver** [comment]
Sorry, @paperboyo, just tried it from the front page to an article, and the same thing still happened: When I clicked Back the page didn't change, but the "Forward one page" button became active. Clicking Back again took me back to the home page. The same happened from the home page to a different article.

Using Windows 8.1, Firefox 41.0.1.

**Comment by paperboyo** [comment]
@niksilver Thanks for checking. Back to the drawing board, then...

**Comment by michaelwmcnamara** [comment]
Reproduced this on FF and on Chrome
Its intermittent but sometimes when you open a piece of content in a new tab the page loads ok, then seems to redraw or reload after the load is complete - it is at this point that the back button suddenly becomes enabled - even though it is a new tab and has no history. Selecting and Holding on the history button show multiple entries of the same page. 
![image](https://cloud.githubusercontent.com/assets/7239344/14326646/d8869b50-fc26-11e5-834a-fa22c34b279f.png)
