### ISSUE TITLE
Tags with special characters don't display correctly

### ISSUE THREAD

**Issue by mstorijo** [guardian/frontend#4012]
See tags here: http://www.theguardian.com/books/2014/apr/17/gabriel-garcia-marquez-obituary

![image](https://cloud.githubusercontent.com/assets/6571215/2815891/88ce1884-cec1-11e3-97f0-0cbe038616fd.png)

**Comment by Jonas-Jancarik** [comment]
Possibly related: user name with special characters is also garbled: JonÃ¡Å¡ JanÄaÅÃ­k
![gruandian encoding](https://cloud.githubusercontent.com/assets/2459191/6031843/fd3e3252-ac02-11e4-9215-478d51e2f13c.PNG)

**Comment by paperboyo** [comment]
Hi, Jonáš!

It looks like something went more wrong than just characters not _displaying_ correctly :-( Does your username display correctly anywhere else on the Guardian site?

Could you give us a link to your user profile, please?

Regards
Mateusz

**Comment by Jonas-Jancarik** [comment]
It's actually fixed now - I have an old account so I had to "confirm my
identity" via Google. Now the special characters are displayed correctly.

Thanks for looking into it anyway!

**Comment by paperboyo** [comment]
Thank you for letting us know! Main issue still present, though.

Regards
Mateusz

**Comment by paperboyo** [comment]
Hello,

Main issue, at least the given example, appears fixed. Safe to close?

Regards
Mateusz

**Comment by Jonas-Jancarik** [comment]
Sorry to disappoint but I've just checked my issue and it seems to be still there. It's fine on my profile https://profile.theguardian.com/user/id/14177071 but when I go to the homepage I see again what's in the screenshot above.

**Comment by michaelwmcnamara** [comment]
Cleanup - closing as this issue is displaying correctly:

![image](https://cloud.githubusercontent.com/assets/7239344/7280057/48f89136-e918-11e4-9a70-f1d1c9154f3f.png)

**Comment by paperboyo** [comment]
Hi, @michaelwmcnamara, what about similar issue reported above by Jonáš (https://github.com/guardian/frontend/issues/4012#issuecomment-72757249)? Should he open a separate issue? It looks like the encoding is permanently garbled - it’s not a font issue... Thanks!

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Reopened due to the mentioned continued issues being experienced and feedback into the inbox. Added sustain flag for this to get another look

**Comment by ScottPainterGNM** [comment]
Actually will create new issue...
