### ISSUE TITLE
Systematic crash

### ISSUE THREAD

**Issue by ddebernardy** [guardian/frontend#5693]
When th beta started, I was able to read the Guardian on my (1st gen) iPad. It was nice and snappy.

More recently, the only thing the site does is crash the iPad's browser. Systematically. Upon trying to load the front page. Noifs, no buts. It crashes, plain and simple, after seemingly succeeding to load the text content. A script in there overwhelms the admittedly pitiful amounts of RAM in the device.

I can still view articles, I think. (Not 100%.) but most assurdly not the front page.

I suspect the problem is the relatively recent intoduction of ads on the beta site, but cannot be 100% since I hadn't been reading the Guardian in a while.

**Comment by ScottPainterGNM** [comment]
Looks like this was resolved via the pull request, closing off to clear the issues list.

**Comment by ddebernardy** [comment]
@ScottPainterGNM - I just tried it. FYI, the front page still crashes the old iPad, but this occurs rarely enough (during redraws, it seems) that it's possible to read the site again. Thanks a lot!

**Comment by ddebernardy** [comment]
FYI it's crashing again. I no longer even try to load the site with JS enabled. But even then, the image assets overwhelm the device.
