### ISSUE TITLE
[urgent] The curious case of disappearing images

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8338]
[UPDATE on reopening: please look at the very bottom of the thread]

Hello,

Not 100% reproducible, unfortunately, every now and then the images show up. Latest beta of FF 36, clean latest Nightly of FF 38 and IE11 on Win 8.1 (Chrome and Opera unaffected). Once happened on a front, but most of the time on a gallery endslate.

Images are not shown (the dark one is because of the hover):
![no images](https://cloud.githubusercontent.com/assets/6032869/6203392/5ebd4938-b517-11e4-97a0-e06e43984215.PNG)

Regards
Mateusz

**Comment by paperboyo** [comment]
And here on a front:
![no images front](https://cloud.githubusercontent.com/assets/6032869/6203419/7085bdce-b519-11e4-88fa-135b5b88b55e.PNG)

**Comment by paperboyo** [comment]
Also on latest release FF 35.0.1 and Safari 7.0.4 on 10.9.3.

**Comment by paperboyo** [comment]
And in more galleries:

![no-images-in-more-galleries](https://cloud.githubusercontent.com/assets/6032869/6215349/98d89e70-b5f7-11e4-80ea-efa614804c26.jpg)

**Comment by Calanthe** [comment]
I can confirm. It is rather easy to reproduce in FF. @michaelwmcnamara how urgent it may be?

**Comment by michaelwmcnamara** [comment]
I can reproduce the issue with gallery recommendations in the lightbox at the end of the gallery - happens reliably.
However the issue with images displayed on fronts I have not been able to reproduce - possibly its been inadvertently fixed in one of the recent deploys.

**Comment by michaelwmcnamara** [comment]
Details with the gallery lightbox recommendations:
To reproduce: 
1) Open any gallery
2) click an image to open lightbox
3) Step through the gallery until the final page using the right-pointing arrow

Result

Recommendations page for other galleries is displayed.
No images shown for any of these galleries

Screenshot for page:
![image](https://cloud.githubusercontent.com/assets/7239344/6352708/63fdfeca-bc3c-11e4-917f-d0036ade55c0.png)


Urls shown in firebug for selected image:
//i.guim.co.uk/static/w-120/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680802460/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-140x84.jpeg 120w, //i.guim.co.uk/static/w-160/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680801274/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-220x132.jpeg 160w, //i.guim.co.uk/static/w-220/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680801274/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-220x132.jpeg 220w, //i.guim.co.uk/static/w-300/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680802991/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-300x180.jpeg 300w, //i.guim.co.uk/static/w-460/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680801839/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-460x276.jpeg 460w, //i.guim.co.uk/static/w-620/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680803570/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-620x372.jpeg 620w

/Pix/pictures/2015/2/23/1424680801274/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-220x132.jpeg 220w, //i.guim.co.uk/static/w-300/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680802991/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-300x180.jpeg 300w, //i.guim.co.uk/static/w-460/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680801839/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-460x276.jpeg 460w, //i.guim.co.uk/static/w-620/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/23/1424680803570/3fd5a856-f8a1-4c37-9a25-5c89770c3f2d-620x372.jpeg 620w

**Comment by paperboyo** [comment]
Hi,

Thank you for picking that up! It's been 9 days. I was wondering if the gallery engagement suffered, but the reports aren't working since around the same time... (https://frontend.gutools.co.uk/analytics/content/gallery - @rich-nguyen).

Couldn't reproduce reliably on fronts and on gallery page at the bottom (more galleries) as well :-(

Thanks again!

Regards
Mateusz


Regards
Mateusz

**Comment by michaelwmcnamara** [comment]
Re Urgency - we should fix this soon, but its urgency is lower owing to the fact that.
I rate it lower than performance issues - which are actually crashing browsers and other fixes to the front currently underway.
a) it is only occurring on the recommendations at the end of the gallery
b) it is only reproduceable on firefox

**Comment by paperboyo** [comment]
Oh, of course! Crashing is much more important!

That was my private urgency! "Urgency", really. And that was more than a week ago ;-)

But what about Safari? IE? I can still reproduce.

**Comment by michaelwmcnamara** [comment]
Good catch - Safari and IE9  also show the issue.
We definitely shoudl fix it - I will ask Alex, Rob or Richard to take a look once they are free.


"It is a very heavy wooden horse my lord"
"hmmm... it must be made of heavy wood"

**Comment by michaelwmcnamara** [comment]
update to this issue - after discussing with Steve, I think it best to hold off on this until the changes to image lazy-loading are put live - reason being, if these changes don't fix the issue outright, they will change the code in the area in which the issue is occuring, so best to wait until this has stabilised than introduce a change in this area which may clash with the bigger changes around lazy-loading that are in the pipeline. This will be fixed in a few days time.

**Comment by paperboyo** [comment]
Hi,

Thanks! Closing then. Will observe and reopen if necessary.

Regards
Mateusz

**Comment by paperboyo** [comment]
Ok. I think it's necessary to reopen this :-(

Firefox 37.0.1 on 10.9.3 today:

![no images](https://cloud.githubusercontent.com/assets/6032869/7565184/b38bc474-f7e5-11e4-8606-ce4a3b2548cd.jpg)

Related to https://github.com/guardian/frontend/issues/8595 where there is an animated GIF showing the problem in question.

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
@paperboyo what were the steps to reproduce this? I have tried Firefox 37.0.2 on 10.10.3 and also emulated 10.9.3 on Browserstack and couldn't replicate the issue?

**Comment by paperboyo** [comment]
@ScottPainterGNM, no 100% reproducible steps, I’m afraid :cry:. I suspect it’s polyfill for picture srcset and/or lazy-loading failing, since it does not happen on any Blink-based browsers... Here is IE11 on Win 8.1 just now:

URL: http://www.theguardian.com/global-development/gallery/2014/dec/08/south-sudanese-displaced-in-pictures (does not matter)
![no images ie11](https://cloud.githubusercontent.com/assets/6032869/7585895/efc00162-f89e-11e4-8f92-4dc62400421e.PNG)

**Comment by paperboyo** [comment]
Still very much an issue! 100% reproducible on IE11 at e.g. http://www.theguardian.com/global-development/gallery/2014/dec/08/south-sudanese-displaced-in-pictures.

**Comment by mattandrews** [comment]
I see this all the time all over the site in Firefox. It seems to only happen when I open pages in a new tab, though...?

**Comment by paperboyo** [comment]
Hi, @mattandrews! This has not happened to me in quite some time in FF (Win+Mac). But I checked just now being curious about your

> It seems to only happen when I open pages in a new tab

I clicked a link to open a gallery page in a new tab and bam! Super-interestingly, the images are there, BUT "more galleries" is empty and footer navigation is all-expanded (is that how the site looks without js?). It happened twice, but now, suddenly, refuses to not work and everything is fine... Baffled...

As to no images, I can't check IE11 now (which was 100% reproducible), but will do at home.

**Comment by sndrs** [comment]
if the bottom nav is expanded and the images aren't loading, that sounds
like a JS error. if you append #noads, do you still get it?

On Thu, 20 Aug 2015 at 11:37 Mateusz <notifications@github.com> wrote:

> Hi, @mattandrews <https://github.com/mattandrews>! This has not happened
> to me in quite some time in FF (Win+Mac). But I checked just now being
> curious about your
>
> It seems to only happen when I open pages in a new tab
>
> I clicked a link to open a gallery page in a new tab and bam!
> Super-interestingly, the images are there, BUT "more galleries" is empty
> and footer navigation is all-expanded (is that how the site looks without
> js?). It happened twice, but now, suddenly, refuses to not work and
> everything is fine... Baffled...
>
> As to no images, I can't check IE11 now (which was 100% reproducible), but
> will do at home.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/8338#issuecomment-132968702>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by paperboyo** [comment]
@sndrs I wouldn't know how to append that to the links opened in new tabs. And, anyway, can't reproduce no js now :sadpanda:

**Comment by mattandrews** [comment]
The JS error I get is documented here: https://github.com/guardian/frontend/issues/9927

My theory: this is some clever JS which does things when the document is "active" or "in focus" or something, which turns out not to play nicely with Firefox's tab setup.

**Comment by mattandrews** [comment]
@sndrs still happens with `#noads` appended when opening links in a new tab in Firefox.

**Comment by paperboyo** [comment]
Can’t reproduce any more. Probably fixed by https://github.com/guardian/frontend/pull/10829. Closing, will reopen (again) if necessary.

**Comment by paperboyo** [comment]
Ha! Saw yesterday on Windows Mobile 8.1 (our testing kit) and today in 7.0.6 (9537.78.2) on 10.9.5. I still somehow think it's related to https://github.com/guardian/frontend/issues/12678 and https://github.com/guardian/frontend/issues/10331 and all the rest of js initialisation errors (although I don't  really know if they are intialisation errors and if they are js errors apart from not knowing if they are related 😆) ...

URL: http://www.theguardian.com/artanddesign/gallery/2016/may/20/fazal-sheikh-erasure-trilogy-pictures-2016-kraszna-krausz-book-award-photographs

![picture 18](https://cloud.githubusercontent.com/assets/6032869/15426804/e07f986e-1e88-11e6-865a-21ed3672a05c.png)

**Comment by paperboyo** [comment]
100% reproducible also in IE11 on Windows 10 (Picturefill?).

**Comment by mchv** [comment]
Debugging with @paperboyo I found something interesting I am going to try to provide a fix!

**Comment by mchv** [comment]
Debugging further with @SiAdcock we have found that `includes` is not available on `Array` at the time the code is executed. `window.guardian.polyfilled` is `false` which means some client side code is executing before the polyfill service which is not expected.

**Comment by paperboyo** [comment]
Closed via https://github.com/guardian/frontend/pull/16527 by the team of heroes led by one @SiAdcock! 💎
